version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Agora Configuration
      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
      - AGORA_CUSTOMER_ID=${AGORA_CUSTOMER_ID}
      - AGORA_CUSTOMER_SECRET=${AGORA_CUSTOMER_SECRET}
      - AGORA_PSTN_AUTH_HEADER=${AGORA_PSTN_AUTH_HEADER}
      - AGORA_PSTN_FROM_NUMBER=${AGORA_PSTN_FROM_NUMBER}
      - AGORA_PSTN_REGION=${AGORA_PSTN_REGION}
      - AGORA_PSTN_API_URL=${AGORA_PSTN_API_URL}
      # MCP Configuration
      - LLM=MCP
      - MCP_SERVER_URL=${MCP_SERVER_URL}
      - MCP_API_KEY=${MCP_API_KEY}
      - MCP_MODEL=${MCP_MODEL}
      # Agent Configuration
      - AGENT_ID=${AGENT_ID}
      - PSTN_UID=${PSTN_UID}
      # Streaming Configuration
      - USE_STREAMING=${USE_STREAMING}
      # External Service APIs
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - CUSTOM_SIP_GATEWAY=${CUSTOM_SIP_GATEWAY}
      - YELP_API_KEY=${YELP_API_KEY}
      # RAG Configuration
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Phone Numbers
      - HERMES_PHONE_NUMBER=${HERMES_PHONE_NUMBER}
      - SID_PHONE_NUMBER=${SID_PHONE_NUMBER}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
