[build]
  base = "."
  command = "npm install -g pnpm@10.5.2 && pnpm install && pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200 