name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create test environment file
        run: |
          cat > .env << EOF
          NODE_ENV=test
          PORT=3001

          # Mock API Keys for testing
          PINECONE_API_KEY=test-pinecone-key
          OPENAI_API_KEY=test-openai-key
          CEREBRAS_API_KEY=test-cerebras-key
          YELP_API_KEY=test-yelp-key

          # Test Database/Service Settings
          PINECONE_INDEX_NAME=test-restaurants
          EMBEDDING_PROVIDER=mock

          # Auth token for integration tests
          AUTH_TOKEN=test-auth-token-12345

          # LLM Provider settings for tests
          LLM=CEREBRAS
          OPENAI_MODEL=gpt-4o-mini
          CEREBRAS_MODEL=llama-4-scout-17b-16e-instruct
          USE_STREAMING=false
          USE_RESPONSES_API=false

          # Required Agora settings (with test values)
          AGORA_APP_ID=test-id
          AGORA_APP_CERTIFICATE=test-cert
          AGORA_CUSTOMER_ID=test-customer
          AGORA_CUSTOMER_SECRET=test-secret
          AGENT_ID=test-agent

          # Additional environment variables for specialized voice agents
          AGORA_CONVO_AI_BASE_URL=https://test-agora-convo-ai.com/api
          LLM_URL=https://test-llm-api.com/v1/chat/completions
          LLM_API_KEY=test-llm-api-key
          LLM_MODEL=test-model
          ELEVENLABS_API_KEY=test-elevenlabs-key
          ELEVENLABS_MODEL_ID=eleven_monolingual_v1
          ELEVENLABS_VOICE_ID=test-voice-id

          # Optional TTS settings
          TTS_VENDOR=elevenlabs
          MICROSOFT_TTS_KEY=test-ms-key
          MICROSOFT_TTS_REGION=test-region
          MICROSOFT_TTS_VOICE_NAME=test-voice
          MICROSOFT_TTS_RATE=1.0
          MICROSOFT_TTS_VOLUME=1.0

          # Optional phone number settings
          HERMES_PHONE_NUMBER=+1234567890
          SID_PHONE_NUMBER=+1234567890

          # Optional PSTN settings
          AGORA_PSTN_AUTH_HEADER=test-auth
          AGORA_PSTN_FROM_NUMBER=+1234567890
          AGORA_PSTN_REGION=test-region
          AGORA_PSTN_API_URL=https://test-pstn-api.com
          PSTN_UID=test-uid
          CUSTOM_SIP_GATEWAY=test-gateway
          EOF

      - name: Lint code
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test:ci

      - name: Run integration tests
        run: pnpm test tests/integration/

      - name: Run existing integration tests
        run: |
          # Run the existing test files (they should pass with mock environment)
          pnpm run test:pinecone || echo "Pinecone tests skipped (expected without real API key)"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: matrix.node-version == '20.x'
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  build-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t custom-llm-cerebras .

      - name: Test Docker image
        run: |
          # Start container in background
          docker run -d -p 3000:3000 --name test-container \
            -e NODE_ENV=test \
            -e CEREBRAS_API_KEY=test-key \
            -e CEREBRAS_MODEL=llama-4-scout-17b-16e-instruct \
            -e LLM=CEREBRAS \
            -e AGORA_APP_ID=test-id \
            -e AGORA_APP_CERTIFICATE=test-cert \
            -e AGORA_CUSTOMER_ID=test-customer \
            -e AGORA_CUSTOMER_SECRET=test-secret \
            -e AGENT_ID=test-agent \
            -e OPENAI_API_KEY=test-openai-key \
            -e PINECONE_API_KEY=test-pinecone-key \
            -e YELP_API_KEY=test-yelp-key \
            -e AUTH_TOKEN=test-auth-token-12345 \
            -e AGORA_CONVO_AI_BASE_URL=https://test-agora-convo-ai.com/api \
            -e LLM_URL=https://test-llm-api.com/v1/chat/completions \
            -e LLM_API_KEY=test-llm-api-key \
            -e ELEVENLABS_API_KEY=test-elevenlabs-key \
            -e ELEVENLABS_MODEL_ID=eleven_monolingual_v1 \
            -e ELEVENLABS_VOICE_ID=test-voice-id \
            custom-llm-cerebras

          # Wait for container to start
          sleep 15

          # Test health endpoint
          curl -f http://localhost:3000/ping || exit 1

          # Cleanup
          docker stop test-container
          docker rm test-container
